##### Tmux status theme #####

set -g mode-style               "fg=#{@theme_accent},bg=#{@theme_muted}"

set -g message-style            "fg=#{@theme_accent},bg=#{@theme_muted}"
set -g message-command-style    "fg=#{@theme_accent},bg=#{@theme_muted}"

set -g pane-border-style        "fg=#{@theme_muted}"
set -g pane-active-border-style "fg=#{@theme_accent}"

set -g status                   "on"
set -g status-justify           "left"

set -g status-style             "fg=#{@theme_accent},bg=#{@theme_background}"

set -g status-left-length       "100"
set -g status-right-length      "100"

set -g status-left-style        NONE
set -g status-right-style       NONE


##### Status Left #####
set -g status-left "#[fg=#{@theme_dark_background},bg=#{@theme_accent},bold] #S \
#[fg=#{@theme_accent},bg=#{@theme_background},nobold,nounderscore,noitalics]"


##### Status Right (12-hour) #####
set -g status-right "#[fg=#{@theme_background},bg=#{@theme_background},nobold,nounderscore,noitalics]\
#[fg=#{@theme_accent},bg=#{@theme_background}] #{prefix_highlight} \
#[fg=#{@theme_muted},bg=#{@theme_background}]\
#[fg=#{@theme_accent},bg=#{@theme_muted}] %Y-%m-%d  %I:%M %p \
#[fg=#{@theme_accent},bg=#{@theme_muted},nobold,nounderscore,noitalics]\
#[fg=#{@theme_dark_background},bg=#{@theme_accent},bold] #h "


##### Status Right (24-hour override) #####
if-shell '[ "$(tmux show-option -gqv "clock-mode-style")" == "24" ]' {
  set -g status-right "#[fg=#{@theme_background},bg=#{@theme_background},nobold,nounderscore,noitalics]\
#[fg=#{@theme_accent},bg=#{@theme_background}] #{prefix_highlight} \
#[fg=#{@theme_muted},bg=#{@theme_background}]\
#[fg=#{@theme_accent},bg=#{@theme_muted}] %Y-%m-%d  %H:%M \
#[fg=#{@theme_accent},bg=#{@theme_muted},nobold,nounderscore,noitalics]\
#[fg=#{@theme_dark_background},bg=#{@theme_accent},bold] #h "
}


##### Window Status #####
setw -g window-status-activity-style "underscore,fg=#{@theme_foreground},bg=#{@theme_background}"
setw -g window-status-separator ""
setw -g window-status-style "none,fg=#{@theme_foreground},bg=#{@theme_background}"

setw -g window-status-format "#[fg=#{@theme_background},bg=#{@theme_background},nobold,nounderscore,noitalics]\
#[default] #I  #W #F \
#[fg=#{@theme_background},bg=#{@theme_background},nobold,nounderscore,noitalics]"

setw -g window-status-current-format "#[fg=#{@theme_background},bg=#{@theme_muted},nobold,nounderscore,noitalics]\
#[fg=#{@theme_accent},bg=#{@theme_muted},bold] #I  #W #F \
#[fg=#{@theme_muted},bg=#{@theme_background},nobold,nounderscore,noitalics]"


##### Prefix Highlight (tmux-prefix-highlight) #####
set -g @prefix_highlight_output_prefix "#[fg=#{@theme_yellow}]#[bg=#{@theme_background}]#[fg=#{@theme_background}]#[bg=#{@theme_yellow}]"
set -g @prefix_highlight_output_suffix ""
