##### Catppuccin Color Variables #####
set -g @theme_accent          "#86B0F3"
set -g @theme_background      "#181825" # this is the bar bg
set -g @theme_dark_background "#1D202F"
set -g @theme_muted           "#313143"
set -g @theme_foreground      "#A9B1D6"
set -g @theme_yellow          "#E0AF68"
