##### Omarchy ANSI Color Variables #####
set -g @theme_accent          "colour4"
set -g @theme_background      "colour0"
set -g @theme_dark_background "colour0"
set -g @theme_muted           "colour8"
set -g @theme_foreground      "colour7"
set -g @theme_yellow          "colour3"
